import { DiscoveryTitle } from '../types';

export const EXPANDED_NETFLIX_CATALOG_TITLES: DiscoveryTitle[] = [
  // --- Mind-Bending, Sci-Fi, Mystery & Time Travel ---
  {
    id: 'exp-sci-1',
    tmdbId: 577922,
    imdbId: 'tt6723592',
    netflixId: '81198930',
    title: 'Tenet',
    originalTitle: 'Tenet',
    mediaType: 'movie',
    releaseYear: 2020,
    posterPath: 'https://image.tmdb.org/t/p/w500/aCIFMriQ2qtLV4Vmxyl7cv59HIW.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/wzJRB4MKi3yK138bEYvZw9ezq14.jpg',
    rating: 7.2,
    imdbRating: 7.3,
    rottenTomatoesRating: 69,
    synopsis: 'Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.',
    genres: ['Action', 'Sci-Fi', 'Thriller'],
    themes: ['mind-bending', 'time travel', 'espionage', 'high stakes', 'puzzle'],
    countries: ['United States', 'United Kingdom'],
    originalLanguage: 'en',
    runtimeMinutes: 150,
    cast: ['John David Washington', 'Robert Pattinson', 'Elizabeth Debicki', 'Kenneth Branagh'],
    director: 'Christopher Nolan',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-sci-2',
    tmdbId: 27205,
    imdbId: 'tt1375666',
    netflixId: '70131314',
    title: 'Inception',
    originalTitle: 'Inception',
    mediaType: 'movie',
    releaseYear: 2010,
    posterPath: 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
    rating: 8.4,
    imdbRating: 8.8,
    rottenTomatoesRating: 87,
    synopsis: 'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets, is offered a chance to regain his old life as payment for a task considered to be impossible: inception.',
    genres: ['Action', 'Sci-Fi', 'Adventure'],
    themes: ['mind-bending', 'heist', 'dreams', 'subconscious', 'puzzle'],
    countries: ['United States', 'United Kingdom'],
    originalLanguage: 'en',
    runtimeMinutes: 148,
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page', 'Tom Hardy'],
    director: 'Christopher Nolan',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-sci-interstellar',
    tmdbId: 157336,
    imdbId: 'tt0816692',
    netflixId: '70305903',
    title: 'Interstellar',
    originalTitle: 'Interstellar',
    mediaType: 'movie',
    releaseYear: 2014,
    posterPath: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
    rating: 8.4,
    imdbRating: 8.7,
    rottenTomatoesRating: 73,
    synopsis: 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    themes: ['deep space', 'black hole', 'time dilation', 'parental sacrifice', 'survival', 'cosmic wonder', 'physics', 'mind-bending'],
    countries: ['United States', 'United Kingdom'],
    originalLanguage: 'en',
    audioLanguages: ['en', 'hi'],
    subtitleLanguages: ['en', 'hi'],
    runtimeMinutes: 169,
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Michael Caine'],
    director: 'Christopher Nolan',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-sci-3',
    tmdbId: 11324,
    imdbId: 'tt1130884',
    netflixId: '70095139',
    title: 'Shutter Island',
    originalTitle: 'Shutter Island',
    mediaType: 'movie',
    releaseYear: 2010,
    posterPath: 'https://image.tmdb.org/t/p/w500/4GDy0PHYX3VRXUtwK5ysagvk2Te.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/cZ0d3rtvXPVvuiX2243x05vFvX7.jpg',
    rating: 8.2,
    imdbRating: 8.2,
    rottenTomatoesRating: 69,
    synopsis: 'World War II soldier-turned-U.S. Marshal Teddy Daniels investigates the disappearance of a patient from Boston\'s Shutter Island Ashecliffe Hospital.',
    genres: ['Drama', 'Mystery', 'Thriller'],
    themes: ['psychological thriller', 'mind-bending', 'conspiracy', 'dark', 'isolated'],
    countries: ['United States'],
    originalLanguage: 'en',
    runtimeMinutes: 138,
    cast: ['Leonardo DiCaprio', 'Mark Ruffalo', 'Ben Kingsley', 'Michelle Williams'],
    director: 'Martin Scorsese',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-sci-4',
    tmdbId: 1949,
    imdbId: 'tt0443706',
    netflixId: '70044697',
    title: 'Zodiac',
    originalTitle: 'Zodiac',
    mediaType: 'movie',
    releaseYear: 2007,
    posterPath: 'https://image.tmdb.org/t/p/w500/6Y0N8H6iZ1B6iW6Rk7m8dY6q5YJ.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/p40x4E7p90b4d06G2gZ8eF8V5q3.jpg',
    rating: 7.6,
    imdbRating: 7.7,
    rottenTomatoesRating: 90,
    synopsis: 'Between 1968 and 1983, a San Francisco cartoonist becomes an amateur detective obsessed with tracking down the Zodiac Killer.',
    genres: ['Crime', 'Drama', 'Mystery', 'Thriller'],
    themes: ['investigative', 'serial killer', 'obsession', 'slow burn', 'true crime'],
    countries: ['United States'],
    originalLanguage: 'en',
    runtimeMinutes: 157,
    cast: ['Jake Gyllenhaal', 'Mark Ruffalo', 'Robert Downey Jr.', 'Anthony Edwards'],
    director: 'David Fincher',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-sci-5',
    tmdbId: 210577,
    imdbId: 'tt2267998',
    netflixId: '70305893',
    title: 'Gone Girl',
    originalTitle: 'Gone Girl',
    mediaType: 'movie',
    releaseYear: 2014,
    posterPath: 'https://image.tmdb.org/t/p/w500/qymaJhucewUwjpbtflKhMMsm1un.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/5y2X8xY7o8eB1a3mX9d2l1a6v8J.jpg',
    rating: 7.9,
    imdbRating: 8.1,
    rottenTomatoesRating: 88,
    synopsis: 'With his wife\'s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it\'s suspected that he may not be innocent.',
    genres: ['Drama', 'Mystery', 'Thriller'],
    themes: ['psychological thriller', 'toxic relationship', 'media frenzy', 'dark', 'plot twist'],
    countries: ['United States'],
    originalLanguage: 'en',
    runtimeMinutes: 149,
    cast: ['Ben Affleck', 'Rosamund Pike', 'Neil Patrick Harris', 'Tyler Perry'],
    director: 'David Fincher',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-sci-6',
    tmdbId: 807,
    imdbId: 'tt0114369',
    netflixId: '950149',
    title: 'Se7en',
    originalTitle: 'Se7en',
    mediaType: 'movie',
    releaseYear: 1995,
    posterPath: 'https://image.tmdb.org/t/p/w500/69Sns8WoET6CfaYlIkHbla4l7nC.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/ba4pvj9W9p7w6mD1pQ9t3z1v8Q0.jpg',
    rating: 8.4,
    imdbRating: 8.6,
    rottenTomatoesRating: 83,
    synopsis: 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.',
    genres: ['Crime', 'Mystery', 'Thriller'],
    themes: ['serial killer', 'dark', 'neo-noir', 'psychological', 'grim'],
    countries: ['United States'],
    originalLanguage: 'en',
    runtimeMinutes: 127,
    cast: ['Brad Pitt', 'Morgan Freeman', 'Gwyneth Paltrow', 'Kevin Spacey'],
    director: 'David Fincher',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-sci-7',
    tmdbId: 1124,
    imdbId: 'tt0482571',
    netflixId: '70047095',
    title: 'The Prestige',
    originalTitle: 'The Prestige',
    mediaType: 'movie',
    releaseYear: 2006,
    posterPath: 'https://image.tmdb.org/t/p/w500/tRNlZbgNCNOpLpbPEz5L8G8A0JN.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/meR2rQ6lB3q0zF5m7W2s3m5V1x9.jpg',
    rating: 8.2,
    imdbRating: 8.5,
    rottenTomatoesRating: 77,
    synopsis: 'After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.',
    genres: ['Drama', 'Mystery', 'Sci-Fi'],
    themes: ['obsession', 'rivalry', 'magic', 'mind-bending', 'plot twist'],
    countries: ['United States', 'United Kingdom'],
    originalLanguage: 'en',
    runtimeMinutes: 130,
    cast: ['Christian Bale', 'Hugh Jackman', 'Scarlett Johansson', 'Michael Caine'],
    director: 'Christopher Nolan',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-sci-8',
    tmdbId: 90669,
    imdbId: 'tt9319668',
    netflixId: '80214497',
    title: '1899',
    originalTitle: '1899',
    mediaType: 'tv',
    releaseYear: 2022,
    posterPath: 'https://image.tmdb.org/t/p/w500/gZ6M11p33nF3rM5i0v9o1s4L0x2.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/1899_backdrop.jpg',
    rating: 7.6,
    imdbRating: 7.4,
    rottenTomatoesRating: 77,
    synopsis: 'Multinational immigrants traveling from the old continent to the new encounter a second ship adrift on the open sea, plunging their journey into a baffling riddle.',
    genres: ['Mystery', 'Drama', 'Sci-Fi'],
    themes: ['mind-bending', 'time travel', 'puzzle', 'simulation', 'dark'],
    countries: ['Germany'],
    originalLanguage: 'en',
    totalSeasons: 1,
    totalEpisodes: 8,
    averageEpisodeMinutes: 60,
    cast: ['Emily Beecham', 'Aneurin Barnard', 'Andreas Pietschmann'],
    creator: 'Jantje Friese & Baran bo Odar',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-sci-9',
    tmdbId: 198102,
    imdbId: 'tt18347622',
    netflixId: '81252916',
    title: 'Bodies',
    originalTitle: 'Bodies',
    mediaType: 'tv',
    releaseYear: 2023,
    posterPath: 'https://image.tmdb.org/t/p/w500/4c3Qc7hNq1H3y4x5m6a7b8c9d0.jpg',
    rating: 7.5,
    imdbRating: 7.4,
    rottenTomatoesRating: 81,
    synopsis: 'Four detectives in four different London eras find the exact same dead body in Whitechapel, uncovering a mysterious conspiracy that spans 150 years.',
    genres: ['Crime', 'Drama', 'Mystery', 'Sci-Fi'],
    themes: ['time travel', 'investigative', 'conspiracy', 'time loop', 'mind-bending'],
    countries: ['United Kingdom'],
    originalLanguage: 'en',
    totalSeasons: 1,
    totalEpisodes: 8,
    averageEpisodeMinutes: 58,
    cast: ['Amaka Okafor', 'Jacob Fortune-Lloyd', 'Kyle Soller', 'Stephen Graham'],
    creator: 'Paul Tomalin',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-sci-10',
    tmdbId: 213713,
    imdbId: 'tt23730310',
    netflixId: '81513251',
    title: 'The Railway Men',
    originalTitle: 'The Railway Men',
    mediaType: 'tv',
    releaseYear: 2023,
    posterPath: 'https://image.tmdb.org/t/p/w500/q2b7b51Q8KovZz2PZ5eTq4PqB6G.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/t0x2c0y9z8d8q1h2k3j4l5m6n7.jpg',
    rating: 8.2,
    imdbRating: 8.5,
    rottenTomatoesRating: 89,
    synopsis: 'After a deadly gas leaks from a factory in Bhopal, brave railway workers risk their lives to save others in the face of an unspeakable catastrophe.',
    genres: ['Drama', 'History', 'Thriller'],
    themes: ['catastrophe', 'bravery', 'disaster', 'real events', 'heroism'],
    countries: ['India'],
    originalLanguage: 'hi',
    totalSeasons: 1,
    totalEpisodes: 4,
    averageEpisodeMinutes: 60,
    cast: ['R. Madhavan', 'Kay Kay Menon', 'Divyenndu', 'Babil Khan'],
    creator: 'Shiv Rawail',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-sci-11',
    tmdbId: 197067,
    imdbId: 'tt2085059',
    netflixId: '80244601',
    title: 'Black Mirror: Bandersnatch',
    originalTitle: 'Black Mirror: Bandersnatch',
    mediaType: 'movie',
    releaseYear: 2018,
    posterPath: 'https://image.tmdb.org/t/p/w500/gTChO1gB0v9z5P1x6W7Q3k7J.jpg',
    rating: 7.2,
    imdbRating: 7.1,
    rottenTomatoesRating: 74,
    synopsis: 'In 1984, a young programmer begins to question reality as he adapts a dark fantasy novel into a video game. A mind-bending interactive psychological odyssey.',
    genres: ['Drama', 'Mystery', 'Sci-Fi', 'Thriller'],
    themes: ['interactive', 'mind-bending', 'simulation', 'madness', 'free will'],
    countries: ['United Kingdom'],
    originalLanguage: 'en',
    runtimeMinutes: 90,
    cast: ['Fionn Whitehead', 'Will Poulter', 'Asim Chaudhry'],
    director: 'David Slade',
    isNetflixIndiaVerified: true,
  },

  // --- Intense Courtroom Drama & Legal Thrillers ---
  {
    id: 'exp-crt-1',
    tmdbId: 37680,
    imdbId: 'tt1632701',
    netflixId: '70195800',
    title: 'Suits',
    originalTitle: 'Suits',
    mediaType: 'tv',
    releaseYear: 2011,
    posterPath: 'https://image.tmdb.org/t/p/w500/vQirMwMfIMPFJioG1ewayOSluHG.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/suits_bg.jpg',
    rating: 8.2,
    imdbRating: 8.4,
    rottenTomatoesRating: 91,
    synopsis: 'While running from a drug deal gone bad, Mike Ross, a brilliant young college-dropout, slips into a job interview with Harvey Specter, one of New York City\'s best legal closers.',
    genres: ['Drama', 'Comedy'],
    themes: ['courtroom drama', 'legal', 'lawyer', 'corporate rivalry', 'sharp dialogue'],
    countries: ['United States'],
    originalLanguage: 'en',
    totalSeasons: 9,
    totalEpisodes: 134,
    averageEpisodeMinutes: 44,
    cast: ['Gabriel Macht', 'Patrick J. Adams', 'Sarah Rafferty', 'Rick Hoffman'],
    creator: 'Aaron Korsh',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-crt-2',
    tmdbId: 60059,
    imdbId: 'tt3032476',
    netflixId: '80025678',
    title: 'Better Call Saul',
    originalTitle: 'Better Call Saul',
    mediaType: 'tv',
    releaseYear: 2015,
    posterPath: 'https://image.tmdb.org/t/p/w500/fC2HDm5t0kHVR79yw0tIGzR59gm.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/bcs_backdrop.jpg',
    rating: 8.7,
    imdbRating: 9.0,
    rottenTomatoesRating: 98,
    synopsis: 'The trials and tribulations of criminal lawyer Jimmy McGill in the years leading up to his fateful run-in with Walter White and Jesse Pinkman.',
    genres: ['Crime', 'Drama'],
    themes: ['legal', 'courtroom drama', 'moral descent', 'grifter', 'character study'],
    countries: ['United States'],
    originalLanguage: 'en',
    totalSeasons: 6,
    totalEpisodes: 63,
    averageEpisodeMinutes: 50,
    cast: ['Bob Odenkirk', 'Rhea Seehorn', 'Jonathan Banks', 'Giancarlo Esposito'],
    creator: 'Vince Gilligan & Peter Gould',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-crt-3',
    tmdbId: 138502,
    imdbId: 'tt13833978',
    netflixId: '81303831',
    title: 'The Lincoln Lawyer',
    originalTitle: 'The Lincoln Lawyer',
    mediaType: 'tv',
    releaseYear: 2022,
    posterPath: 'https://image.tmdb.org/t/p/w500/7aA8pW2h0e3eB8k9w2a1b3c4d5.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/lincolnlawyer_bg.jpg',
    rating: 7.8,
    imdbRating: 7.7,
    rottenTomatoesRating: 85,
    synopsis: 'Mickey Haller, an iconoclastic idealist, runs his law practice out of the back of his Lincoln Town Car, taking on cases big and small across Los Angeles.',
    genres: ['Crime', 'Drama', 'Mystery'],
    themes: ['courtroom drama', 'legal thriller', 'lawyer', 'trial', 'investigative'],
    countries: ['United States'],
    originalLanguage: 'en',
    totalSeasons: 3,
    totalEpisodes: 30,
    averageEpisodeMinutes: 50,
    cast: ['Manuel Garcia-Rulfo', 'Neve Campbell', 'Becki Newton', 'Jazz Raycole'],
    creator: 'David E. Kelley',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-crt-4',
    tmdbId: 114695,
    imdbId: 'tt12361974',
    netflixId: '81198642',
    title: 'Anatomy of a Scandal',
    originalTitle: 'Anatomy of a Scandal',
    mediaType: 'tv',
    releaseYear: 2022,
    posterPath: 'https://image.tmdb.org/t/p/w500/anatomy_scandal.jpg',
    rating: 7.1,
    imdbRating: 7.0,
    rottenTomatoesRating: 68,
    synopsis: 'A psychological thriller and gripping courtroom drama about sexual consent and privilege among British elites, centered on a high-profile rape trial at the Old Bailey.',
    genres: ['Drama', 'Mystery', 'Thriller'],
    themes: ['courtroom drama', 'legal battle', 'scandal', 'privilege', 'trial'],
    countries: ['United Kingdom'],
    originalLanguage: 'en',
    totalSeasons: 1,
    totalEpisodes: 6,
    averageEpisodeMinutes: 45,
    cast: ['Sienna Miller', 'Michelle Dockery', 'Rupert Friend', 'Naomi Scott'],
    creator: 'David E. Kelley & Melissa James Gibson',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-crt-5',
    tmdbId: 615658,
    imdbId: 'tt9735462',
    netflixId: '81242987',
    title: 'Section 375',
    originalTitle: 'Section 375',
    mediaType: 'movie',
    releaseYear: 2019,
    posterPath: 'https://image.tmdb.org/t/p/w500/x7rVZ0KiPWxBMJBI8roIwlMvs2c.jpg',
    rating: 7.8,
    imdbRating: 8.1,
    rottenTomatoesRating: 83,
    synopsis: 'A celebrated Bollywood director is accused of rape by a female crew member. A high-stakes courtroom battle ensues where two sharp advocates clash over evidence and the law.',
    genres: ['Crime', 'Drama', 'Thriller'],
    themes: ['courtroom drama', 'legal thriller', 'moral ambiguity', 'intense trial', 'arguments'],
    countries: ['India'],
    originalLanguage: 'hi',
    runtimeMinutes: 124,
    cast: ['Akshaye Khanna', 'Richa Chadha', 'Rahul Bhat', 'Meera Chopra'],
    director: 'Ajay Bahl',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-crt-6',
    tmdbId: 801335,
    imdbId: 'tt14152738',
    netflixId: '81504316',
    title: 'Darlings',
    originalTitle: 'Darlings',
    mediaType: 'movie',
    releaseYear: 2022,
    posterPath: 'https://image.tmdb.org/t/p/w500/z6Dq1rI0qYxX3l2q2pQf9d8m6.jpg',
    rating: 7.3,
    imdbRating: 7.2,
    rottenTomatoesRating: 78,
    synopsis: 'Badru hopes her volatile husband will reform if he stops drinking. But when his rage goes too far, she and her audacious mother boldly seek revenge.',
    genres: ['Comedy', 'Crime', 'Drama'],
    themes: ['dark comedy', 'revenge', 'domestic struggle', 'twisted plan'],
    countries: ['India'],
    originalLanguage: 'hi',
    runtimeMinutes: 134,
    cast: ['Alia Bhatt', 'Shefali Shah', 'Vijay Varma', 'Roshan Mathew'],
    director: 'Jasmeet K. Reen',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-crt-7',
    tmdbId: 556984,
    imdbId: 'tt1070874',
    netflixId: '81303038',
    title: 'The Trial of the Chicago 7',
    originalTitle: 'The Trial of the Chicago 7',
    mediaType: 'movie',
    releaseYear: 2020,
    posterPath: 'https://image.tmdb.org/t/p/w500/ahf5cVdooMAlDRiJOZQNuLqa1Is.jpg',
    rating: 7.7,
    imdbRating: 7.7,
    rottenTomatoesRating: 89,
    synopsis: 'What was intended to be a peaceful protest at the 1968 Democratic National Convention turned into a violent clash with police. The organizers were charged with conspiracy to incite a riot in one of the most notorious trials in history.',
    genres: ['Drama', 'History', 'Thriller'],
    themes: ['courtroom drama', 'politics', 'protest', 'civil rights', 'sorkin dialogue'],
    countries: ['United States'],
    originalLanguage: 'en',
    runtimeMinutes: 129,
    cast: ['Eddie Redmayne', 'Sacha Baron Cohen', 'Mark Rylance', 'Joseph Gordon-Levitt'],
    director: 'Aaron Sorkin',
    isNetflixIndiaVerified: true,
  },

  // --- Documentaries & Docuseries ---
  {
    id: 'exp-doc-1',
    tmdbId: 77708,
    imdbId: 'tt7262580',
    netflixId: '80145240',
    title: 'Wild Wild Country',
    originalTitle: 'Wild Wild Country',
    mediaType: 'tv',
    releaseYear: 2018,
    posterPath: 'https://image.tmdb.org/t/p/w500/wild_wild_country.jpg',
    rating: 8.1,
    imdbRating: 8.1,
    rottenTomatoesRating: 98,
    synopsis: 'When the world\'s most controversial guru builds a utopian city deep in the Oregon desert, conflict with the locals escalates into an unprecedented national scandal involving bioterrorism and wiretapping.',
    genres: ['Documentary', 'Crime'],
    themes: ['cult', 'conspiracy', 'true story', 'religion', 'bizarre'],
    countries: ['United States'],
    originalLanguage: 'en',
    totalSeasons: 1,
    totalEpisodes: 6,
    averageEpisodeMinutes: 64,
    cast: ['Bhagwan Shree Rajneesh', 'Ma Anand Sheela', 'Jane Stork'],
    director: 'Maclain Way & Chapman Way',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-doc-2',
    tmdbId: 85937,
    imdbId: 'tt8289930',
    netflixId: '80204890',
    title: 'Formula 1: Drive to Survive',
    originalTitle: 'Formula 1: Drive to Survive',
    mediaType: 'tv',
    releaseYear: 2019,
    posterPath: 'https://image.tmdb.org/t/p/w500/xGOGjJFYYeRSoOpnhN9IHZTXIxj.jpg',
    rating: 8.2,
    imdbRating: 8.5,
    rottenTomatoesRating: 90,
    synopsis: 'Drivers, managers and team owners live life in the fast lane - both on and off the track - during each cutthroat season of Formula 1 racing.',
    genres: ['Documentary', 'Sport'],
    themes: ['high adrenaline', 'motorsport', 'rivalry', 'behind the scenes', 'sports drama'],
    countries: ['United Kingdom'],
    originalLanguage: 'en',
    totalSeasons: 6,
    totalEpisodes: 60,
    averageEpisodeMinutes: 40,
    cast: ['Lewis Hamilton', 'Max Verstappen', 'Christian Horner', 'Toto Wolff', 'Guenther Steiner'],
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-doc-3',
    tmdbId: 87802,
    imdbId: 'tt8463714',
    netflixId: '80203144',
    title: 'The Last Dance',
    originalTitle: 'The Last Dance',
    mediaType: 'tv',
    releaseYear: 2020,
    posterPath: 'https://image.tmdb.org/t/p/w500/oVf4xGGbDtwVHiKn8uTuSriY7PH.jpg',
    rating: 8.6,
    imdbRating: 9.1,
    rottenTomatoesRating: 97,
    synopsis: 'A definitive 10-part documentary chronicles Michael Jordan and the 1990s Chicago Bulls dynasty, packed with never-before-seen footage of their 1997-98 championship season.',
    genres: ['Documentary', 'Sport', 'Biography'],
    themes: ['basketball', 'greatness', 'obsession', 'sports', 'legend'],
    countries: ['United States'],
    originalLanguage: 'en',
    totalSeasons: 1,
    totalEpisodes: 10,
    averageEpisodeMinutes: 50,
    cast: ['Michael Jordan', 'Scottie Pippen', 'Dennis Rodman', 'Phil Jackson'],
    director: 'Jason Hehir',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-doc-4',
    tmdbId: 135754,
    imdbId: 'tt15510614',
    netflixId: '81094586',
    title: 'House of Secrets: The Burari Deaths',
    originalTitle: 'House of Secrets: The Burari Deaths',
    mediaType: 'tv',
    releaseYear: 2021,
    posterPath: 'https://image.tmdb.org/t/p/w500/burari_deaths.jpg',
    rating: 7.5,
    imdbRating: 7.4,
    rottenTomatoesRating: 88,
    synopsis: 'Suicide, murder... or something else? This chilling docuseries examines the eerie truths and theories around the deaths of 11 members of a Delhi family discovered hanging inside their home.',
    genres: ['Documentary', 'Crime', 'Mystery'],
    themes: ['true crime', 'psychological', 'mystery', 'superstition', 'investigative'],
    countries: ['India'],
    originalLanguage: 'hi',
    totalSeasons: 1,
    totalEpisodes: 3,
    averageEpisodeMinutes: 45,
    director: 'Leena Yadav',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-doc-5',
    tmdbId: 96647,
    imdbId: 'tt11318602',
    netflixId: '81031373',
    title: 'Don\'t F**k with Cats: Hunting an Internet Killer',
    originalTitle: 'Don\'t F**k with Cats: Hunting an Internet Killer',
    mediaType: 'tv',
    releaseYear: 2019,
    posterPath: 'https://image.tmdb.org/t/p/w500/dont_fk_with_cats.jpg',
    rating: 7.9,
    imdbRating: 8.0,
    rottenTomatoesRating: 93,
    synopsis: 'When a disturbing video of a hooded figure killing kittens is uploaded online, an international group of online sleuths launch a relentless manhunt that leads them to a psychopathic murderer.',
    genres: ['Documentary', 'Crime', 'Mystery'],
    themes: ['internet sleuths', 'manhunt', 'psychopath', 'true crime', 'disturbing'],
    countries: ['United States', 'United Kingdom'],
    originalLanguage: 'en',
    totalSeasons: 1,
    totalEpisodes: 3,
    averageEpisodeMinutes: 60,
    director: 'Mark Lewis',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-doc-6',
    tmdbId: 736733,
    imdbId: 'tt11464826',
    netflixId: '81254224',
    title: 'The Social Dilemma',
    originalTitle: 'The Social Dilemma',
    mediaType: 'movie',
    releaseYear: 2020,
    posterPath: 'https://image.tmdb.org/t/p/w500/social_dilemma.jpg',
    rating: 7.6,
    imdbRating: 7.6,
    rottenTomatoesRating: 85,
    synopsis: 'Tech insiders and experts explore the dangerous human impact of social networking, with technology designed to manipulate behaviour and destabilize democracy.',
    genres: ['Documentary', 'Drama'],
    themes: ['social media', 'algorithms', 'tech addiction', 'surveillance capitalism'],
    countries: ['United States'],
    originalLanguage: 'en',
    runtimeMinutes: 94,
    director: 'Jeff Orlowski-Yang',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-doc-7',
    tmdbId: 923985,
    imdbId: 'tt16447040',
    netflixId: '81260278',
    title: 'The Tinder Swindler',
    originalTitle: 'The Tinder Swindler',
    mediaType: 'movie',
    releaseYear: 2022,
    posterPath: 'https://image.tmdb.org/t/p/w500/tinder_swindler.jpg',
    rating: 7.1,
    imdbRating: 7.1,
    rottenTomatoesRating: 84,
    synopsis: 'Posing as a wealthy, jet-setting diamond mogul, a conman wooed women online and swindled them out of millions of dollars. Several victims band together to fight back.',
    genres: ['Documentary', 'Crime'],
    themes: ['con artist', 'romance scam', 'investigative', 'revenge'],
    countries: ['United Kingdom'],
    originalLanguage: 'en',
    runtimeMinutes: 114,
    director: 'Felicity Morris',
    isNetflixIndiaVerified: true,
  },

  // --- Anime Masterpieces ---
  {
    id: 'exp-ani-1',
    tmdbId: 13916,
    imdbId: 'tt0877057',
    netflixId: '70204970',
    title: 'Death Note',
    originalTitle: 'デスノート',
    mediaType: 'tv',
    releaseYear: 2006,
    posterPath: 'https://image.tmdb.org/t/p/w500/iigTJJskR1Pcjj4xBge5A8nv4vU.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/deathnote_bg.jpg',
    rating: 8.6,
    imdbRating: 9.0,
    rottenTomatoesRating: 96,
    synopsis: 'Light Yagami finds a supernatural notebook that grants the ability to kill anyone whose name and face he knows. He sets out to cleanse the world of evil, sparking a cat-and-mouse battle of wits with the genius detective L.',
    genres: ['Animation', 'Mystery', 'Psychological', 'Thriller'],
    themes: ['battle of wits', 'cat-and-mouse', 'supernatural', 'justice vs morality', 'mastermind'],
    countries: ['Japan'],
    originalLanguage: 'ja',
    totalSeasons: 1,
    totalEpisodes: 37,
    averageEpisodeMinutes: 23,
    cast: ['Mamoru Miyano', 'Kappei Yamaguchi', 'Shidou Nakamura'],
    creator: 'Tsugumi Ohba & Takeshi Obata',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-ani-2',
    tmdbId: 94605,
    imdbId: 'tt11126994',
    netflixId: '81435684',
    title: 'Arcane',
    originalTitle: 'Arcane',
    mediaType: 'tv',
    releaseYear: 2021,
    posterPath: 'https://image.tmdb.org/t/p/w500/fq2yE39K0Vb7K5l1e7r1y8X0s9.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/arcane_bg.jpg',
    rating: 8.7,
    imdbRating: 9.0,
    rottenTomatoesRating: 100,
    synopsis: 'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and incompatible convictions.',
    genres: ['Animation', 'Action', 'Sci-Fi', 'Fantasy', 'Drama'],
    themes: ['steampunk', 'sisterhood', 'dystopian', 'masterpiece animation', 'tragic'],
    countries: ['United States', 'France'],
    originalLanguage: 'en',
    totalSeasons: 2,
    totalEpisodes: 18,
    averageEpisodeMinutes: 42,
    cast: ['Hailee Steinfeld', 'Ella Purnell', 'Kevin Alejandro'],
    creator: 'Christian Linke & Alex Yee',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-ani-3',
    tmdbId: 83095,
    imdbId: 'tt10233448',
    netflixId: '81249833',
    title: 'Vinland Saga',
    originalTitle: 'ヴィンランド・サガ',
    mediaType: 'tv',
    releaseYear: 2019,
    posterPath: 'https://image.tmdb.org/t/p/w500/vUHlpA5c1NXkds59reY3HMb4Abs.jpg',
    rating: 8.5,
    imdbRating: 8.8,
    rottenTomatoesRating: 94,
    synopsis: 'Thorfinn pursues a journey of revenge against the mercenary leader who killed his father, becoming trapped in the bloody wars for the English crown.',
    genres: ['Animation', 'Action', 'Adventure', 'Drama'],
    themes: ['vikings', 'revenge to pacifism', 'historical', 'dark', 'masterpiece'],
    countries: ['Japan'],
    originalLanguage: 'ja',
    totalSeasons: 2,
    totalEpisodes: 48,
    averageEpisodeMinutes: 24,
    cast: ['Yuto Uemura', 'Naoya Uchida', 'Kensho Ono'],
    creator: 'Makoto Yukimura',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-ani-4',
    tmdbId: 46298,
    imdbId: 'tt0434706',
    netflixId: '80045000',
    title: 'Monster',
    originalTitle: 'MONSTER',
    mediaType: 'tv',
    releaseYear: 2004,
    posterPath: 'https://image.tmdb.org/t/p/w500/monster_anime.jpg',
    rating: 8.7,
    imdbRating: 8.7,
    rottenTomatoesRating: 98,
    synopsis: 'Dr. Kenzo Tenma, a brilliant Japanese neurosurgeon in Germany, saves the life of a young boy instead of the mayor. Years later, he discovers that the boy grew up to become a charismatic sociopathic monster.',
    genres: ['Animation', 'Crime', 'Drama', 'Mystery', 'Psychological'],
    themes: ['psychological thriller', 'sociopath', 'cat-and-mouse', 'philosophical', 'dark mystery'],
    countries: ['Japan'],
    originalLanguage: 'ja',
    totalSeasons: 1,
    totalEpisodes: 74,
    averageEpisodeMinutes: 24,
    cast: ['Hidenobu Kiuchi', 'Tsutomu Isobe', 'Mamiko Noto'],
    creator: 'Naoki Urasawa',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-ani-5',
    tmdbId: 71912,
    imdbId: 'tt6517102',
    netflixId: '80095241',
    title: 'Castlevania',
    originalTitle: 'Castlevania',
    mediaType: 'tv',
    releaseYear: 2017,
    posterPath: 'https://image.tmdb.org/t/p/w500/WzFHnJY44uDERER0xi1jOdoafT.jpg',
    rating: 8.3,
    imdbRating: 8.3,
    rottenTomatoesRating: 94,
    synopsis: 'A vampire hunter fights to save a besieged city from an army of otherworldly beasts controlled by Dracula himself after the human execution of his beloved wife.',
    genres: ['Animation', 'Action', 'Fantasy', 'Horror'],
    themes: ['vampires', 'dark fantasy', 'gothic', 'brutal action', 'revenge'],
    countries: ['United States'],
    originalLanguage: 'en',
    totalSeasons: 4,
    totalEpisodes: 32,
    averageEpisodeMinutes: 25,
    cast: ['Richard Armitage', 'James Callis', 'Graham McTavish'],
    creator: 'Warren Ellis',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-ani-6',
    tmdbId: 105248,
    imdbId: 'tt12590266',
    netflixId: '81054853',
    title: 'Cyberpunk: Edgerunners',
    originalTitle: 'Cyberpunk: Edgerunners',
    mediaType: 'tv',
    releaseYear: 2022,
    posterPath: 'https://image.tmdb.org/t/p/w500/7jSW0L9nMsH7z0g8i02w.jpg',
    rating: 8.6,
    imdbRating: 8.3,
    rottenTomatoesRating: 100,
    synopsis: 'A street kid trying to survive in a technology and body modification-obsessed city of the future decides to stay alive by becoming an edgerunner: a mercenary outlaw.',
    genres: ['Animation', 'Action', 'Sci-Fi'],
    themes: ['cyberpunk', 'dystopian', 'body modification', 'high-octane action', 'tragedy'],
    countries: ['Poland', 'Japan'],
    originalLanguage: 'ja',
    totalSeasons: 1,
    totalEpisodes: 10,
    averageEpisodeMinutes: 24,
    cast: ['KENN', 'Aoi Yuki', 'Hiroki Touchi'],
    creator: 'Hiroyuki Imaishi',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-ani-7',
    tmdbId: 76121,
    imdbId: 'tt7203672',
    netflixId: '80177749',
    title: 'Devilman Crybaby',
    originalTitle: 'DEVILMAN crybaby',
    mediaType: 'tv',
    releaseYear: 2018,
    posterPath: 'https://image.tmdb.org/t/p/w500/7eZqXp1u1V3D3x8w.jpg',
    rating: 7.9,
    imdbRating: 7.6,
    rottenTomatoesRating: 89,
    synopsis: 'With demons reawakened and humanity in turmoil, a sensitive demon-boy is led into a brutal, degenerate war against evil by his mysterious friend.',
    genres: ['Animation', 'Action', 'Fantasy', 'Horror'],
    themes: ['dark fantasy', 'apocalypse', 'demons', 'visceral', 'existential'],
    countries: ['Japan'],
    originalLanguage: 'ja',
    totalSeasons: 1,
    totalEpisodes: 10,
    averageEpisodeMinutes: 25,
    cast: ['Koki Uchiyama', 'Ayumu Murase', 'Megumi Han'],
    creator: 'Masaaki Yuasa',
    isNetflixIndiaVerified: true,
  },

  // --- K-Dramas & Asian Thrillers ---
  {
    id: 'exp-kd-1',
    tmdbId: 117376,
    imdbId: 'tt13433802',
    netflixId: '81365219',
    title: 'Vincenzo',
    originalTitle: '빈센조',
    mediaType: 'tv',
    releaseYear: 2021,
    posterPath: 'https://image.tmdb.org/t/p/w500/qbkSS1cTjT4DzIwD44bdhTuYgdT.jpg',
    rating: 8.4,
    imdbRating: 8.4,
    rottenTomatoesRating: 96,
    synopsis: 'During a visit to his motherland, a Korean-Italian mafia lawyer gives an unrivaled conglomerate a taste of its own medicine with a side of vicious justice.',
    genres: ['Action', 'Comedy', 'Crime', 'Drama'],
    themes: ['anti-hero', 'mafia', 'dark comedy', 'corporate takedown', 'stylish'],
    countries: ['South Korea'],
    originalLanguage: 'ko',
    totalSeasons: 1,
    totalEpisodes: 20,
    averageEpisodeMinutes: 80,
    cast: ['Song Joong-ki', 'Jeon Yeo-been', 'Ok Taec-yeon'],
    creator: 'Park Jae-bum',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-kd-2',
    tmdbId: 70593,
    imdbId: 'tt8584884',
    netflixId: '80180171',
    title: 'Kingdom',
    originalTitle: '킹덤',
    mediaType: 'tv',
    releaseYear: 2019,
    posterPath: 'https://image.tmdb.org/t/p/w500/kingdom_kdrama.jpg',
    rating: 8.2,
    imdbRating: 8.3,
    rottenTomatoesRating: 98,
    synopsis: 'While strange rumors about their ill King grip a kingdom, the Crown Prince becomes their only hope against a mysterious plague overtaking the land in Joseon-era Korea.',
    genres: ['Action', 'Drama', 'Horror', 'Mystery'],
    themes: ['zombies', 'historical', 'palace politics', 'survival', 'intense'],
    countries: ['South Korea'],
    originalLanguage: 'ko',
    totalSeasons: 2,
    totalEpisodes: 12,
    averageEpisodeMinutes: 50,
    cast: ['Ju Ji-hoon', 'Ryu Seung-ryong', 'Bae Doona'],
    creator: 'Kim Eun-hee',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-kd-3',
    tmdbId: 110356,
    imdbId: 'tt12915716',
    netflixId: '81298665',
    title: 'Alice in Borderland',
    originalTitle: '今際の国のアリス',
    mediaType: 'tv',
    releaseYear: 2020,
    posterPath: 'https://image.tmdb.org/t/p/w500/alice_in_borderland.jpg',
    rating: 8.2,
    imdbRating: 7.7,
    rottenTomatoesRating: 88,
    synopsis: 'An obsessed gamer and his two friends find themselves in an emptied version of Tokyo, where they are forced to compete in dangerous, mind-bending games in order to survive.',
    genres: ['Action', 'Drama', 'Mystery', 'Sci-Fi', 'Thriller'],
    themes: ['death games', 'survival', 'psychological puzzle', 'hooked first episode', 'dystopian'],
    countries: ['Japan'],
    originalLanguage: 'ja',
    totalSeasons: 2,
    totalEpisodes: 16,
    averageEpisodeMinutes: 50,
    cast: ['Kento Yamazaki', 'Tao Tsuchiya', 'Nijiro Murakami'],
    creator: 'Shinsuke Sato',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-kd-4',
    tmdbId: 129888,
    imdbId: 'tt14274488',
    netflixId: '81011211',
    title: 'My Name',
    originalTitle: '마이 네임',
    mediaType: 'tv',
    releaseYear: 2021,
    posterPath: 'https://image.tmdb.org/t/p/w500/gHozOomiA24DvlgNfjkYCB5NBiO.jpg',
    rating: 8.2,
    imdbRating: 7.8,
    rottenTomatoesRating: 86,
    synopsis: 'Following her father\'s murder, a revenge-driven woman puts her trust in a powerful crime boss - and enters the police force under his direction to find the killer.',
    genres: ['Action', 'Crime', 'Drama', 'Thriller'],
    themes: ['undercover', 'revenge', 'gritty action', 'noir', 'martial arts'],
    countries: ['South Korea'],
    originalLanguage: 'ko',
    totalSeasons: 1,
    totalEpisodes: 8,
    averageEpisodeMinutes: 50,
    cast: ['Han So-hee', 'Park Hee-soon', 'Ahn Bo-hyun'],
    director: 'Kim Jin-min',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-kd-5',
    tmdbId: 96162,
    imdbId: 'tt11239552',
    netflixId: '81193309',
    title: 'Itaewon Class',
    originalTitle: '이태원 클라쓰',
    mediaType: 'tv',
    releaseYear: 2020,
    posterPath: 'https://image.tmdb.org/t/p/w500/itaewon_class.jpg',
    rating: 8.2,
    imdbRating: 8.2,
    rottenTomatoesRating: 92,
    synopsis: 'In a colorful Seoul neighborhood, an ex-con and his misfit staff fight to make their ambitious pub dreams a reality against a ruthless corporate food dynasty.',
    genres: ['Drama', 'Romance'],
    themes: ['underdog', 'revenge', 'entrepreneurship', 'friendship', 'determination'],
    countries: ['South Korea'],
    originalLanguage: 'ko',
    totalSeasons: 1,
    totalEpisodes: 16,
    averageEpisodeMinutes: 70,
    cast: ['Park Seo-jun', 'Kim Da-mi', 'Yoo Jae-myung'],
    creator: 'Gwang Jin',
    isNetflixIndiaVerified: true,
  },

  // --- Hooked on First Episode & Fast-Paced Thrillers ---
  {
    id: 'exp-fst-1',
    tmdbId: 2288,
    imdbId: 'tt0455275',
    netflixId: '70140425',
    title: 'Prison Break',
    originalTitle: 'Prison Break',
    mediaType: 'tv',
    releaseYear: 2005,
    posterPath: 'https://image.tmdb.org/t/p/w500/prison_break.jpg',
    rating: 8.1,
    imdbRating: 8.3,
    rottenTomatoesRating: 88,
    synopsis: 'An engineer installs himself in a maximum security prison he helped design, in order to break out his falsely accused brother sentenced to death.',
    genres: ['Action', 'Crime', 'Drama', 'Thriller'],
    themes: ['prison escape', 'hooked first episode', 'fast paced', 'master plan', 'cliffhangers'],
    countries: ['United States'],
    originalLanguage: 'en',
    totalSeasons: 5,
    totalEpisodes: 90,
    averageEpisodeMinutes: 44,
    cast: ['Wentworth Miller', 'Dominic Purcell', 'Sarah Wayne Callies', 'Robert Knepper'],
    creator: 'Paul Scheuring',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-fst-2',
    tmdbId: 124834,
    imdbId: 'tt14269590',
    netflixId: '81450829',
    title: 'Beef',
    originalTitle: 'BEEF',
    mediaType: 'tv',
    releaseYear: 2023,
    posterPath: 'https://image.tmdb.org/t/p/w500/25ih0Xq2zWbxhhKxwhvswKYQyEr.jpg',
    rating: 8.0,
    imdbRating: 8.0,
    rottenTomatoesRating: 98,
    synopsis: 'A road rage incident between two strangers - a failing contractor and an unfulfilled entrepreneur - sparks a feud that brings out their darkest impulses.',
    genres: ['Comedy', 'Drama'],
    themes: ['road rage', 'chaos', 'obsession', 'dark comedy', 'hooked first episode'],
    countries: ['United States'],
    originalLanguage: 'en',
    totalSeasons: 1,
    totalEpisodes: 10,
    averageEpisodeMinutes: 34,
    cast: ['Steven Yeun', 'Ali Wong', 'Joseph Lee', 'Young Mazino'],
    creator: 'Lee Sung Jin',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-fst-3',
    tmdbId: 154825,
    imdbId: 'tt13918776',
    netflixId: '81450830',
    title: 'The Night Agent',
    originalTitle: 'The Night Agent',
    mediaType: 'tv',
    releaseYear: 2023,
    posterPath: 'https://image.tmdb.org/t/p/w500/night_agent.jpg',
    rating: 7.6,
    imdbRating: 7.5,
    rottenTomatoesRating: 75,
    synopsis: 'A vigilant FBI agent manning an emergency phone in the White House basement answers a call that plunges him into a deadly conspiracy involving a mole in high command.',
    genres: ['Action', 'Drama', 'Thriller'],
    themes: ['fast paced', 'conspiracy', 'fbi', 'hooked first episode', 'espionage'],
    countries: ['United States'],
    originalLanguage: 'en',
    totalSeasons: 1,
    totalEpisodes: 10,
    averageEpisodeMinutes: 50,
    cast: ['Gabriel Basso', 'Luciane Buchanan', 'Fola Evans-Akingbola'],
    creator: 'Shawn Ryan',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-fst-4',
    tmdbId: 78191,
    imdbId: 'tt7493974',
    netflixId: '80235864',
    title: 'Bodyguard',
    originalTitle: 'Bodyguard',
    mediaType: 'tv',
    releaseYear: 2018,
    posterPath: 'https://image.tmdb.org/t/p/w500/bodyguard_bbc.jpg',
    rating: 7.9,
    imdbRating: 8.1,
    rottenTomatoesRating: 93,
    synopsis: 'A heroic war veteran is assigned to protect the ambitious Home Secretary whose politics stand for everything he despises. The first 20 minutes feature an unforgettable train standoff.',
    genres: ['Crime', 'Drama', 'Thriller'],
    themes: ['intense opening', 'bodyguard', 'political thriller', 'ptsd', 'fast paced'],
    countries: ['United Kingdom'],
    originalLanguage: 'en',
    totalSeasons: 1,
    totalEpisodes: 6,
    averageEpisodeMinutes: 60,
    cast: ['Richard Madden', 'Keeley Hawes', 'Gina McKee'],
    creator: 'Jed Mercurio',
    isNetflixIndiaVerified: true,
  },

  // --- Acclaimed Indian Series & Blockbusters ---
  {
    id: 'exp-ind-1',
    tmdbId: 226998,
    imdbId: 'tt26543880',
    netflixId: '81454048',
    title: 'Scoop',
    originalTitle: 'Scoop',
    mediaType: 'tv',
    releaseYear: 2023,
    posterPath: 'https://image.tmdb.org/t/p/w500/uU8c0u6V5w4q3X4y5z6a7b8c9.jpg',
    rating: 7.8,
    imdbRating: 7.7,
    rottenTomatoesRating: 88,
    synopsis: 'The shocking murder of a journalist thrusts a leading crime reporter into a nexus of police, media, and the Mumbai underworld as she fights to clear her name.',
    genres: ['Crime', 'Drama'],
    themes: ['journalism', 'underworld', 'mumbai crime', 'investigative', 'true story'],
    countries: ['India'],
    originalLanguage: 'hi',
    totalSeasons: 1,
    totalEpisodes: 6,
    averageEpisodeMinutes: 55,
    cast: ['Karishma Tanna', 'Mohammed Zeeshan Ayyub', 'Harman Baweja', 'Prosenjit Chatterjee'],
    creator: 'Hansal Mehta',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-ind-2',
    tmdbId: 213702,
    imdbId: 'tt22878776',
    netflixId: '81285741',
    title: 'Khakee: The Bihar Chapter',
    originalTitle: 'Khakee: The Bihar Chapter',
    mediaType: 'tv',
    releaseYear: 2022,
    posterPath: 'https://image.tmdb.org/t/p/w500/khakee_bihar.jpg',
    rating: 8.0,
    imdbRating: 8.2,
    rottenTomatoesRating: 85,
    synopsis: 'As a righteous cop pursues a merciless criminal in Bihar, he finds himself navigating a deadly chase and a moral battle mired in corruption.',
    genres: ['Action', 'Crime', 'Drama'],
    themes: ['police', 'bihar underworld', 'gangster', 'justice', 'gritty crime'],
    countries: ['India'],
    originalLanguage: 'hi',
    totalSeasons: 1,
    totalEpisodes: 7,
    averageEpisodeMinutes: 48,
    cast: ['Karan Tacker', 'Avinash Tiwary', 'Abhimanyu Singh', 'Ashutosh Rana'],
    creator: 'Neeraj Pandey',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-ind-3',
    tmdbId: 115782,
    imdbId: 'tt1954470',
    netflixId: '70259074',
    title: 'Gangs of Wasseypur',
    originalTitle: 'Gangs of Wasseypur',
    mediaType: 'movie',
    releaseYear: 2012,
    posterPath: 'https://image.tmdb.org/t/p/w500/gangs_of_wasseypur.jpg',
    rating: 8.1,
    imdbRating: 8.2,
    rottenTomatoesRating: 97,
    synopsis: 'A clash between Sultan and Shahid Khan leads to the expulsion of Khan from Wasseypur, igniting a deadly blood feud that spans three generations of coal mafia.',
    genres: ['Action', 'Comedy', 'Crime', 'Drama'],
    themes: ['generational blood feud', 'coal mafia', 'cult classic', 'epic crime saga'],
    countries: ['India'],
    originalLanguage: 'hi',
    runtimeMinutes: 321,
    cast: ['Manoj Bajpayee', 'Nawazuddin Siddiqui', 'Richa Chadha', 'Huma Qureshi'],
    director: 'Anurag Kashyap',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-ind-4',
    tmdbId: 353491,
    imdbId: 'tt4430212',
    netflixId: '80068153',
    title: 'Drishyam',
    originalTitle: 'Drishyam',
    mediaType: 'movie',
    releaseYear: 2015,
    posterPath: 'https://image.tmdb.org/t/p/w500/drishyam_hindi.jpg',
    rating: 8.2,
    imdbRating: 8.2,
    rottenTomatoesRating: 85,
    synopsis: 'Desperate measures are taken by a movie-obsessed cable operator who tries to save his family from the dark side of the law after they commit an unexpected crime.',
    genres: ['Crime', 'Drama', 'Mystery', 'Thriller'],
    themes: ['perfect alibi', 'family protection', 'cat-and-mouse with police', 'mastermind'],
    countries: ['India'],
    originalLanguage: 'hi',
    runtimeMinutes: 163,
    cast: ['Ajay Devgn', 'Tabu', 'Shriya Saran', 'Kamlesh Sawant'],
    director: 'Nishikant Kamat',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-ind-5',
    tmdbId: 708304,
    imdbId: 'tt12477382',
    netflixId: '81029150',
    title: 'Bulbbul',
    originalTitle: 'Bulbbul',
    mediaType: 'movie',
    releaseYear: 2020,
    posterPath: 'https://image.tmdb.org/t/p/w500/bK0a4qgQh6Yx1X1o2pQf9d8m6.jpg',
    rating: 7.2,
    imdbRating: 6.6,
    rottenTomatoesRating: 88,
    synopsis: 'A child bride grows into an enigmatic woman ruling over her household, harboring a painful past as supernatural murders of men plague her village.',
    genres: ['Drama', 'Fantasy', 'Horror'],
    themes: ['folklore', 'gothic horror', 'feminism', 'atmosphere', 'mystery'],
    countries: ['India'],
    originalLanguage: 'hi',
    runtimeMinutes: 94,
    cast: ['Triptii Dimri', 'Avinash Tiwary', 'Paoli Dam', 'Rahul Bose'],
    director: 'Anvita Dutt',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-ind-6',
    tmdbId: 1133519,
    imdbId: 'tt27918244',
    netflixId: '81681534',
    title: 'Amar Singh Chamkila',
    originalTitle: 'Amar Singh Chamkila',
    mediaType: 'movie',
    releaseYear: 2024,
    posterPath: 'https://image.tmdb.org/t/p/w500/chamkila_netflix.jpg',
    rating: 8.1,
    imdbRating: 7.9,
    rottenTomatoesRating: 92,
    synopsis: 'A humble singer\'s brash lyrics ignite fame and fury across Punjab as he grapples with soaring success and brutal criticism before his untimely death.',
    genres: ['Biography', 'Drama', 'Music'],
    themes: ['music biography', 'punjab', 'cultural icon', 'controversy', 'artistic freedom'],
    countries: ['India'],
    originalLanguage: 'hi',
    runtimeMinutes: 147,
    cast: ['Vikrant Massey', 'Medha Shankr', 'Anant V Joshi', 'Geeta Agrawal Sharma'],
    director: 'Vidhu Vinod Chopra',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-ind-7',
    tmdbId: 1025527,
    imdbId: 'tt26250350',
    netflixId: '81490450',
    title: 'Guns & Gulaabs',
    originalTitle: 'Guns & Gulaabs',
    mediaType: 'tv',
    releaseYear: 2023,
    posterPath: 'https://image.tmdb.org/t/p/w500/guns_gulaabs.jpg',
    rating: 7.7,
    imdbRating: 7.7,
    rottenTomatoesRating: 83,
    synopsis: 'In the cartel-run town of Gulaabganj, an unprecedented opium deal pulls a big-city cop and a lovesick mechanic into its chaotic, bloody crosshairs in 1990s India.',
    genres: ['Comedy', 'Crime', 'Romance', 'Thriller'],
    themes: ['retro', 'dark comedy', 'nostalgia', 'gangsters', 'quirky'],
    countries: ['India'],
    originalLanguage: 'hi',
    totalSeasons: 1,
    totalEpisodes: 7,
    averageEpisodeMinutes: 50,
    cast: ['Rajkummar Rao', 'Dulquer Salmaan', 'Gulshan Devaiah', 'Adarsh Gourav'],
    creator: 'Raj & DK',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-ind-8',
    tmdbId: 216390,
    imdbId: 'tt18274874',
    netflixId: '81490455',
    title: 'Kaala Paani',
    originalTitle: 'Kaala Paani',
    mediaType: 'tv',
    releaseYear: 2023,
    posterPath: 'https://image.tmdb.org/t/p/w500/kaala_paani.jpg',
    rating: 8.0,
    imdbRating: 8.0,
    rottenTomatoesRating: 89,
    synopsis: 'When a mysterious deadly epidemic strikes the isolated Andaman and Nicobar Islands, desperate people struggle to survive while doctors race to find a cure before it\'s too late.',
    genres: ['Drama', 'Mystery', 'Sci-Fi', 'Thriller'],
    themes: ['survival', 'epidemic', 'island isolation', 'human nature', 'fast paced'],
    countries: ['India'],
    originalLanguage: 'hi',
    totalSeasons: 1,
    totalEpisodes: 7,
    averageEpisodeMinutes: 60,
    cast: ['Mona Singh', 'Ashutosh Gowariker', 'Amey Wagh', 'Sukant Goel'],
    creator: 'Sameer Saxena',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-ind-9',
    tmdbId: 1118224,
    imdbId: 'tt27663544',
    netflixId: '81757829',
    title: 'Maharaja',
    originalTitle: 'Maharaja',
    mediaType: 'movie',
    releaseYear: 2024,
    posterPath: 'https://image.tmdb.org/t/p/w500/s0m4TM1XRAftQStgKpw024RvkJo.jpg',
    rating: 8.4,
    imdbRating: 8.5,
    rottenTomatoesRating: 94,
    synopsis: 'A quiet barber approaches the police reporting that his house was burglarized and his dustbin \'Lakshmi\' stolen. The bizarre report hides an earth-shattering quest for revenge.',
    genres: ['Action', 'Crime', 'Drama', 'Thriller'],
    themes: ['mind-bending timeline', 'revenge', 'father daughter', 'plot twist', 'dark'],
    countries: ['India'],
    originalLanguage: 'ta',
    runtimeMinutes: 141,
    cast: ['Vijay Sethupathi', 'Anurag Kashyap', 'Mamta Mohandas', 'Natty'],
    director: 'Nithilan Saminathan',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-ind-10',
    tmdbId: 1242372,
    imdbId: 'tt31046944',
    netflixId: '81765432',
    title: 'Sector 36',
    originalTitle: 'Sector 36',
    mediaType: 'movie',
    releaseYear: 2024,
    posterPath: 'https://image.tmdb.org/t/p/w500/pbVcZmmcfqk35Q9hNxRoR7JPiVp.jpg',
    rating: 7.4,
    imdbRating: 7.2,
    rottenTomatoesRating: 80,
    synopsis: 'Inspired by true events: when several children go missing from a slum in Sector 36, a corrupt police officer is forced to pursue a cunning serial killer who operates in plain sight.',
    genres: ['Crime', 'Drama', 'Thriller'],
    themes: ['serial killer', 'true crime', 'dark', 'police procedural', 'tense'],
    countries: ['India'],
    originalLanguage: 'hi',
    runtimeMinutes: 124,
    cast: ['Vikrant Massey', 'Deepak Dobriyal', 'Akash Khurana'],
    director: 'Aditya Nimbalkar',
    isNetflixIndiaVerified: true,
  },

  // --- Sci-Fi & Blockbuster Action ---
  {
    id: 'exp-act-1',
    tmdbId: 438631,
    imdbId: 'tt1160419',
    netflixId: '81198934',
    title: 'Dune',
    originalTitle: 'Dune',
    mediaType: 'movie',
    releaseYear: 2021,
    posterPath: 'https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/dune_bg.jpg',
    rating: 7.8,
    imdbRating: 8.0,
    rottenTomatoesRating: 83,
    synopsis: 'Paul Atreides, a brilliant young man born into a great destiny, must travel to the most dangerous planet in the universe to ensure the future of his family and people.',
    genres: ['Adventure', 'Sci-Fi'],
    themes: ['epic sci-fi', 'desert planet', 'prophecy', 'politics', 'visual masterpiece'],
    countries: ['United States'],
    originalLanguage: 'en',
    runtimeMinutes: 155,
    cast: ['Timothée Chalamet', 'Rebecca Ferguson', 'Oscar Isaac', 'Zendaya'],
    director: 'Denis Villeneuve',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-act-2',
    tmdbId: 335984,
    imdbId: 'tt1856101',
    netflixId: '80185760',
    title: 'Blade Runner 2049',
    originalTitle: 'Blade Runner 2049',
    mediaType: 'movie',
    releaseYear: 2017,
    posterPath: 'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/br2049_bg.jpg',
    rating: 8.0,
    imdbRating: 8.0,
    rottenTomatoesRating: 88,
    synopsis: 'Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what\'s left of society into chaos.',
    genres: ['Drama', 'Mystery', 'Sci-Fi'],
    themes: ['cyberpunk', 'existential', 'neo-noir', 'visual masterpiece', 'slow burn'],
    countries: ['United States'],
    originalLanguage: 'en',
    runtimeMinutes: 164,
    cast: ['Ryan Gosling', 'Harrison Ford', 'Ana de Armas', 'Sylvia Hoeks'],
    director: 'Denis Villeneuve',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-act-3',
    tmdbId: 603,
    imdbId: 'tt0133093',
    netflixId: '20557937',
    title: 'The Matrix',
    originalTitle: 'The Matrix',
    mediaType: 'movie',
    releaseYear: 1999,
    posterPath: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    rating: 8.2,
    imdbRating: 8.7,
    rottenTomatoesRating: 88,
    synopsis: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    genres: ['Action', 'Sci-Fi'],
    themes: ['simulation', 'cyberpunk', 'kung fu', 'philosophical', 'bullet time'],
    countries: ['United States'],
    originalLanguage: 'en',
    runtimeMinutes: 136,
    cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss', 'Hugo Weaving'],
    director: 'Lana Wachowski & Lilly Wachowski',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-act-4',
    tmdbId: 693134,
    imdbId: 'tt13139366',
    netflixId: '81098494',
    title: 'Extraction 2',
    originalTitle: 'Extraction 2',
    mediaType: 'movie',
    releaseYear: 2023,
    posterPath: 'https://image.tmdb.org/t/p/w500/7gKI9hpEMcZUwJwNgkPnR9R462o.jpg',
    rating: 7.5,
    imdbRating: 7.0,
    rottenTomatoesRating: 79,
    synopsis: 'Back from the brink of death, highly skilled black ops commando Tyler Rake takes on another dangerous mission: saving the imprisoned family of a ruthless gangster.',
    genres: ['Action', 'Thriller'],
    themes: ['oner action scene', 'high adrenaline', 'mercenary', 'gunplay', 'fast paced'],
    countries: ['United States'],
    originalLanguage: 'en',
    runtimeMinutes: 122,
    cast: ['Chris Hemsworth', 'Golshifteh Farahani', 'Adam Bessa', 'Tornike Gogrichiani'],
    director: 'Sam Hargrave',
    isNetflixIndiaVerified: true,
  },

  // --- Comedy & Quirky Cult Favorites ---
  {
    id: 'exp-com-1',
    tmdbId: 48891,
    imdbId: 'tt2467372',
    netflixId: '70281562',
    title: 'Brooklyn Nine-Nine',
    originalTitle: 'Brooklyn Nine-Nine',
    mediaType: 'tv',
    releaseYear: 2013,
    posterPath: 'https://image.tmdb.org/t/p/w500/mpjlDzVjp7oyHUe2LaF9ltKe6f1.jpg',
    rating: 8.2,
    imdbRating: 8.4,
    rottenTomatoesRating: 95,
    synopsis: 'Comedy series following the exploits of Det. Jake Peralta and his diverse, lovable colleagues as they police the NYPD\'s 99th Precinct under strict Captain Raymond Holt.',
    genres: ['Comedy', 'Crime'],
    themes: ['workplace comedy', 'detective', 'feel good', 'lovable ensemble', 'hilarious'],
    countries: ['United States'],
    originalLanguage: 'en',
    totalSeasons: 8,
    totalEpisodes: 153,
    averageEpisodeMinutes: 22,
    cast: ['Andy Samberg', 'Stephanie Beatriz', 'Terry Crews', 'Melissa Fumero', 'Andre Braugher'],
    creator: 'Dan Goor & Michael Schur',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-com-2',
    tmdbId: 66573,
    imdbId: 'tt4955642',
    netflixId: '80113701',
    title: 'The Good Place',
    originalTitle: 'The Good Place',
    mediaType: 'tv',
    releaseYear: 2016,
    posterPath: 'https://image.tmdb.org/t/p/w500/good_place.jpg',
    rating: 8.0,
    imdbRating: 8.2,
    rottenTomatoesRating: 97,
    synopsis: 'When Eleanor Shellstrop dies and ends up in the afterlife \'Good Place\' by mistake, she is determined to become a better person to keep from being found out.',
    genres: ['Comedy', 'Drama', 'Fantasy'],
    themes: ['philosophy', 'ethics', 'afterlife', 'plot twists', 'heartwarming'],
    countries: ['United States'],
    originalLanguage: 'en',
    totalSeasons: 4,
    totalEpisodes: 53,
    averageEpisodeMinutes: 22,
    cast: ['Kristen Bell', 'Ted Danson', 'William Jackson Harper', 'Jameela Jamil'],
    creator: 'Michael Schur',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-com-3',
    tmdbId: 60625,
    imdbId: 'tt2861424',
    netflixId: '80057281',
    title: 'Rick and Morty',
    originalTitle: 'Rick and Morty',
    mediaType: 'tv',
    releaseYear: 2013,
    posterPath: 'https://image.tmdb.org/t/p/w500/cvhNj9eoRBe5SxjUQURQTnWcuNA.jpg',
    rating: 8.7,
    imdbRating: 9.1,
    rottenTomatoesRating: 92,
    synopsis: 'An eccentric, alcoholic sociopath scientist and his good-hearted but fretful grandson embark on insane interdimensional misadventures across time and parallel universes.',
    genres: ['Animation', 'Comedy', 'Sci-Fi'],
    themes: ['multiverse', 'cynical humor', 'mind-bending', 'nihilism', 'absurdist'],
    countries: ['United States'],
    originalLanguage: 'en',
    totalSeasons: 7,
    totalEpisodes: 71,
    averageEpisodeMinutes: 22,
    cast: ['Justin Roiland', 'Chris Parnell', 'Spencer Grammer', 'Sarah Chalke'],
    creator: 'Dan Harmon & Justin Roiland',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-com-4',
    tmdbId: 61222,
    imdbId: 'tt3398228',
    netflixId: '70300800',
    title: 'BoJack Horseman',
    originalTitle: 'BoJack Horseman',
    mediaType: 'tv',
    releaseYear: 2014,
    posterPath: 'https://image.tmdb.org/t/p/w500/6JFWzlChcGgLiIUo2COgNlWGFKy.jpg',
    rating: 8.6,
    imdbRating: 8.8,
    rottenTomatoesRating: 93,
    synopsis: 'Meet the most beloved sitcom horse of the \'90s - 20 years later. He\'s a curmudgeon with a heart of... not quite gold... but something like gold. Dark existential comedy masterwork.',
    genres: ['Animation', 'Comedy', 'Drama'],
    themes: ['existential dread', 'hollywood satire', 'mental health', 'addiction', 'masterpiece'],
    countries: ['United States'],
    originalLanguage: 'en',
    totalSeasons: 6,
    totalEpisodes: 77,
    averageEpisodeMinutes: 25,
    cast: ['Will Arnett', 'Amy Sedaris', 'Alison Brie', 'Aaron Paul'],
    creator: 'Raphael Bob-Waksberg',
    isNetflixIndiaVerified: true,
  },
  {
    id: 'exp-com-5',
    tmdbId: 76092,
    imdbId: 'tt7124614',
    netflixId: '80238565',
    title: 'Derry Girls',
    originalTitle: 'Derry Girls',
    mediaType: 'tv',
    releaseYear: 2018,
    posterPath: 'https://image.tmdb.org/t/p/w500/9b2N70eU4E2l4cT8p5x1Q9y8z7a.jpg',
    rating: 8.3,
    imdbRating: 8.5,
    rottenTomatoesRating: 99,
    synopsis: 'Amidst the political conflict of Northern Ireland in the 1990s, five high school friends navigate the turbulent universal trials of teen life.',
    genres: ['Comedy'],
    themes: ['coming of age', 'dark comedy', '90s nostalgia', 'friendship', 'hilarious'],
    countries: ['United Kingdom'],
    originalLanguage: 'en',
    totalSeasons: 3,
    totalEpisodes: 19,
    averageEpisodeMinutes: 24,
    cast: ['Saoirse-Monica Jackson', 'Louisa Harland', 'Nicola Coughlan', 'Jamie-Lee O\'Donnell'],
    creator: 'Lisa McGee',
    isNetflixIndiaVerified: true,
  },
];
