import { EpisodeInfo, TrailerInfo } from '../types';

export interface SampleMetadata {
  mediaType: 'movie' | 'tv';
  externalId: number;
  externalTitle: string;
  releaseYear: number;
  posterPath: string;
  backdropPath?: string;
  rating: number;
  voteCount: number;
  synopsis: string;
  genres: string[];
  runtimeMinutes?: number;
  totalSeasons?: number;
  totalEpisodes?: number;
  averageEpisodeMinutes?: number;
  episodes?: EpisodeInfo[];
  trailer?: TrailerInfo;
}

export const SAMPLE_METADATA_MAP: Record<string, SampleMetadata> = {
  '100humans': {
    mediaType: 'tv',
    externalId: 99427,
    externalTitle: "100 Humans: Life's Questions. Answered.",
    releaseYear: 2020,
    posterPath: "https://image.tmdb.org/t/p/w500/9kC9wV3Y0OQY9gV1zI0zV6Z6jL3.jpg",
    backdropPath: "https://image.tmdb.org/t/p/w1280/aI7yK9P4h9l1t6A5p5z1v4v7a1.jpg",
    rating: 7.2,
    voteCount: 140,
    synopsis: "One hundred hardy souls from diverse backgrounds take part in playful experiments exploring age, sex, happiness and other aspects of being human.",
    genres: ["Reality", "Documentary"],
    totalSeasons: 1,
    totalEpisodes: 8,
    averageEpisodeMinutes: 34,
    episodes: [
      { id: 101, seasonNumber: 1, episodeNumber: 1, name: "What Makes Us Attractive?", runtimeMinutes: 35 },
      { id: 102, seasonNumber: 1, episodeNumber: 2, name: "The Best Age to Be Alive", runtimeMinutes: 33 },
      { id: 103, seasonNumber: 1, episodeNumber: 3, name: "Let's Talk About Sex", runtimeMinutes: 36 },
      { id: 104, seasonNumber: 1, episodeNumber: 4, name: "Are You Biased?", runtimeMinutes: 32 },
      { id: 105, seasonNumber: 1, episodeNumber: 5, name: "Pain vs Pleasure", runtimeMinutes: 34 },
      { id: 106, seasonNumber: 1, episodeNumber: 6, name: "How to Be Happy", runtimeMinutes: 35 },
      { id: 107, seasonNumber: 1, episodeNumber: 7, name: "Can We Trust Our Senses?", runtimeMinutes: 33 },
      { id: 108, seasonNumber: 1, episodeNumber: 8, name: "Ask a Human", runtimeMinutes: 31 },
    ],
    trailer: {
      id: "t1",
      key: "6n9ERvW8u44",
      name: "Official Trailer",
      site: "YouTube",
      type: "Trailer",
      language: "en",
    },
  },
  '14peaksnothingisimpossible': {
    mediaType: 'movie',
    externalId: 887163,
    externalTitle: "14 Peaks: Nothing Is Impossible",
    releaseYear: 2021,
    posterPath: "https://image.tmdb.org/t/p/w500/y6wGZ5eMbm67sK0V96K4iG92Q5.jpg",
    backdropPath: "https://image.tmdb.org/t/p/w1280/8tU8sZ3Y0OQY9gV1zI0zV6Z6jL3.jpg",
    rating: 7.9,
    voteCount: 460,
    synopsis: "Fearless Nepali mountaineer Nimsdai Purja embarks on a seemingly impossible quest to summit all 14 of the world's 8,000-meter peaks in seven months.",
    genres: ["Documentary", "Adventure"],
    runtimeMinutes: 101,
    trailer: {
      id: "t2",
      key: "8QH5hBOoz08",
      name: "Official Trailer",
      site: "YouTube",
      type: "Trailer",
      language: "en",
    },
  },
  '28dayshaunted': {
    mediaType: 'tv',
    externalId: 211910,
    externalTitle: "28 Days Haunted",
    releaseYear: 2022,
    posterPath: "https://image.tmdb.org/t/p/w500/wA2J54E4uXf8qV7z1V8JkL54z2.jpg",
    rating: 5.8,
    voteCount: 95,
    synopsis: "Three teams each spend 28 days in America's most haunted locations for a paranormal experiment based on the theories of Ed and Lorraine Warren.",
    genres: ["Reality", "Horror"],
    totalSeasons: 1,
    totalEpisodes: 6,
    averageEpisodeMinutes: 39,
    episodes: [
      { id: 201, seasonNumber: 1, episodeNumber: 1, name: "The Experiment Begins", runtimeMinutes: 42 },
      { id: 202, seasonNumber: 1, episodeNumber: 2, name: "The Gateway", runtimeMinutes: 38 },
      { id: 203, seasonNumber: 1, episodeNumber: 3, name: "Paranormal Activity", runtimeMinutes: 40 },
      { id: 204, seasonNumber: 1, episodeNumber: 4, name: "Possession", runtimeMinutes: 37 },
      { id: 205, seasonNumber: 1, episodeNumber: 5, name: "Breaking Point", runtimeMinutes: 39 },
      { id: 206, seasonNumber: 1, episodeNumber: 6, name: "Final Reckoning", runtimeMinutes: 41 },
    ],
  },
  '3': {
    mediaType: 'tv',
    externalId: 68615,
    externalTitle: "3%",
    releaseYear: 2016,
    posterPath: "https://image.tmdb.org/t/p/w500/uUom55Zf5hXn97p39Z4M1t1l4c6.jpg",
    rating: 7.4,
    voteCount: 1450,
    synopsis: "In a future where the elite inhabit an island paradise far from the crowded slums, you get one chance to join the 3% saved from squalor.",
    genres: ["Action & Adventure", "Sci-Fi & Fantasy", "Drama"],
    totalSeasons: 4,
    totalEpisodes: 33,
    averageEpisodeMinutes: 45,
    episodes: [
      { id: 301, seasonNumber: 1, episodeNumber: 1, name: "Chapter 01: Cubes", runtimeMinutes: 49 },
      { id: 302, seasonNumber: 1, episodeNumber: 2, name: "Chapter 02: Coins", runtimeMinutes: 44 },
      { id: 303, seasonNumber: 1, episodeNumber: 3, name: "Chapter 03: Corridor", runtimeMinutes: 43 },
      { id: 304, seasonNumber: 1, episodeNumber: 4, name: "Chapter 04: Gateway", runtimeMinutes: 48 },
      { id: 305, seasonNumber: 1, episodeNumber: 5, name: "Chapter 05: Water", runtimeMinutes: 47 },
      { id: 306, seasonNumber: 1, episodeNumber: 6, name: "Chapter 06: Glass", runtimeMinutes: 43 },
      { id: 307, seasonNumber: 1, episodeNumber: 7, name: "Chapter 07: Capsule", runtimeMinutes: 45 },
      { id: 308, seasonNumber: 1, episodeNumber: 8, name: "Chapter 08: Button", runtimeMinutes: 49 },
      { id: 309, seasonNumber: 2, episodeNumber: 1, name: "Chapter 09: Mirror", runtimeMinutes: 45 },
      { id: 310, seasonNumber: 2, episodeNumber: 2, name: "Chapter 10: Toaster", runtimeMinutes: 46 },
    ],
    trailer: {
      id: "t3",
      key: "8ZgXkQ3aB8A",
      name: "Official Trailer",
      site: "YouTube",
      type: "Trailer",
      language: "en",
    },
  },
  '7prisoners': {
    mediaType: 'movie',
    externalId: 785538,
    externalTitle: "7 Prisoners",
    releaseYear: 2021,
    posterPath: "https://image.tmdb.org/t/p/w500/yv9VjXlB9gXkQ3aB8A2V7z1V8Jk.jpg",
    rating: 7.1,
    voteCount: 310,
    synopsis: "To provide a better life for his family in the country, 18-year-old Mateus accepts a job in a São Paulo junkyard for his new boss, Luca, but becomes trapped in the dangerous world of human trafficking.",
    genres: ["Drama"],
    runtimeMinutes: 94,
  },
  'thebatman': {
    mediaType: 'movie',
    externalId: 414906,
    externalTitle: "The Batman",
    releaseYear: 2022,
    posterPath: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    backdropPath: "https://image.tmdb.org/t/p/w1280/tRS6jvPM9qPrrnx2KRk3ew96YKd.jpg",
    rating: 8.1,
    voteCount: 9450,
    synopsis: "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
    genres: ["Action", "Crime", "Drama"],
    runtimeMinutes: 176,
    trailer: {
      id: "t_bat",
      key: "mqqft2x_Aa4",
      name: "The Batman – Main Trailer",
      site: "YouTube",
      type: "Trailer",
      language: "en",
    },
  },
  'dark': {
    mediaType: 'tv',
    externalId: 70523,
    externalTitle: "Dark",
    releaseYear: 2017,
    posterPath: "https://image.tmdb.org/t/p/w500/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg",
    backdropPath: "https://image.tmdb.org/t/p/w1280/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
    rating: 8.7,
    voteCount: 6200,
    synopsis: "A missing child sets four families on a frantic hunt for answers as they uncover a mind-bending mystery that spans three generations.",
    genres: ["Sci-Fi & Fantasy", "Drama", "Mystery"],
    totalSeasons: 3,
    totalEpisodes: 26,
    averageEpisodeMinutes: 49,
    episodes: [
      { id: 401, seasonNumber: 1, episodeNumber: 1, name: "Secrets", runtimeMinutes: 52 },
      { id: 402, seasonNumber: 1, episodeNumber: 2, name: "Lies", runtimeMinutes: 45 },
      { id: 403, seasonNumber: 1, episodeNumber: 3, name: "Past and Present", runtimeMinutes: 46 },
      { id: 404, seasonNumber: 1, episodeNumber: 4, name: "Double Lives", runtimeMinutes: 48 },
      { id: 405, seasonNumber: 1, episodeNumber: 5, name: "Truths", runtimeMinutes: 46 },
      { id: 406, seasonNumber: 1, episodeNumber: 6, name: "Sic Mundus Creatus Est", runtimeMinutes: 51 },
      { id: 407, seasonNumber: 1, episodeNumber: 7, name: "Crossroads", runtimeMinutes: 52 },
      { id: 408, seasonNumber: 1, episodeNumber: 8, name: "As You Sow, So You Shall Reap", runtimeMinutes: 50 },
      { id: 409, seasonNumber: 1, episodeNumber: 9, name: "Everything is Now", runtimeMinutes: 56 },
      { id: 410, seasonNumber: 1, episodeNumber: 10, name: "Alpha and Omega", runtimeMinutes: 57 },
    ],
    trailer: {
      id: "t_dark",
      key: "rrwycJ08PSA",
      name: "Dark Official Trailer",
      site: "YouTube",
      type: "Trailer",
      language: "en",
    },
  },
  'theglory': {
    mediaType: 'tv',
    externalId: 136283,
    externalTitle: "The Glory",
    releaseYear: 2022,
    posterPath: "https://image.tmdb.org/t/p/w500/6jOpyXV9JlMf5nwtjn1L3tT4vS8.jpg",
    backdropPath: "https://image.tmdb.org/t/p/w1280/vGvF2e5zM8xV4k0f1f1d1f5v5z.jpg",
    rating: 8.6,
    voteCount: 520,
    synopsis: "After surviving awful abuse in high school, a woman puts an elaborate revenge scheme in motion to make the perpetrators pay for their crimes.",
    genres: ["Drama", "Crime"],
    totalSeasons: 1,
    totalEpisodes: 16,
    averageEpisodeMinutes: 55,
    episodes: [
      { id: 501, seasonNumber: 1, episodeNumber: 1, name: "Episode 1", runtimeMinutes: 54 },
      { id: 502, seasonNumber: 1, episodeNumber: 2, name: "Episode 2", runtimeMinutes: 53 },
      { id: 503, seasonNumber: 1, episodeNumber: 3, name: "Episode 3", runtimeMinutes: 56 },
      { id: 504, seasonNumber: 1, episodeNumber: 4, name: "Episode 4", runtimeMinutes: 55 },
      { id: 505, seasonNumber: 1, episodeNumber: 5, name: "Episode 5", runtimeMinutes: 57 },
      { id: 506, seasonNumber: 1, episodeNumber: 6, name: "Episode 6", runtimeMinutes: 54 },
      { id: 507, seasonNumber: 1, episodeNumber: 7, name: "Episode 7", runtimeMinutes: 56 },
      { id: 508, seasonNumber: 1, episodeNumber: 8, name: "Episode 8", runtimeMinutes: 55 },
      { id: 509, seasonNumber: 1, episodeNumber: 9, name: "Episode 9", runtimeMinutes: 54 },
      { id: 510, seasonNumber: 1, episodeNumber: 10, name: "Episode 10", runtimeMinutes: 60 },
    ],
    trailer: {
      id: "t_glory",
      key: "tqFF5fsm2K8",
      name: "The Glory | Official Trailer",
      site: "YouTube",
      type: "Trailer",
      language: "en",
    },
  },
};
